
const product = [
    {
        id:"1",
        name:"",
        image:require('../assets/dress.1')
    },
    {
        id:"2",
        name:"",
        image:require('../assets/dress.2')
    },
    {
        id:"3",
        name:"",
        image:require('../assets/dress.3')
    },
    {
        id:"4",
        name:"",
        image:require('../assets/dress.4')
    },
    {
        id:"5",
        name:"",
        image:require('../assets/dress.5')
    },
    {
        id:"6",
        name:"",
        image:require('../assets/dress.6')
    },
    {
        id:"7",
        name:"",
        image:require('../assets/dress.7')
    },
]